name: ğŸ³ Docker Image CI

on:
  push:
    branches: [ "features" ]
  pull_request:
    branches: [ "features" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”¨ Build Docker image with timestamp tag
        run: |
          docker build . \
            --file Dockerfile \
            --tag my-image-name:$(date +%Y%m%d%H%M%S)
